// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neubrutalism-portfolio/Classic.tsx": () => import("../components/mockups/neubrutalism-portfolio/Classic.tsx"),
  "./components/mockups/neubrutalism-portfolio/Colorful.tsx": () => import("../components/mockups/neubrutalism-portfolio/Colorful.tsx"),
  "./components/mockups/neubrutalism-portfolio/Dark.tsx": () => import("../components/mockups/neubrutalism-portfolio/Dark.tsx")
};
